/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_hsr_hapdroid_NetworkCapture */

#ifndef _Included_ch_hsr_hapdroid_NetworkCapture
#define _Included_ch_hsr_hapdroid_NetworkCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_hsr_hapdroid_NetworkCapture
 * Method:    startCapture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_hsr_hapdroid_NetworkCapture_startCapture
  (JNIEnv *, jclass);

/*
 * Class:     ch_hsr_hapdroid_NetworkCapture
 * Method:    getResult
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_hsr_hapdroid_NetworkCapture_getResult
  (JNIEnv *, jclass);

/*
 * Class:     ch_hsr_hapdroid_NetworkCapture
 * Method:    stopCapture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_hsr_hapdroid_NetworkCapture_stopCapture
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
