/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_hsr_hapdroid_HAPvizLibrary */

#ifndef _Included_ch_hsr_hapdroid_HAPvizLibrary
#define _Included_ch_hsr_hapdroid_HAPvizLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_hsr_hapdroid_HAPvizLibrary
 * Method:    getTransactions
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ch_hsr_hapdroid_HAPvizLibrary_getTransactions__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     ch_hsr_hapdroid_HAPvizLibrary
 * Method:    getTransactions
 * Signature: ([BLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ch_hsr_hapdroid_HAPvizLibrary_getTransactions___3BLjava_lang_String_2
  (JNIEnv *, jclass, jbyteArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
